excel_django/config/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("excel.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excel_django/excel/urls.py
from django.urls import path
from . import views

app_name    = "excel"
urlpatterns = [
    path('', views.index, name="index"),
    path('download/<int:pk>/', views.download, name="download"),
]

excel_django/excel/models.py
from django.db import models

class Document(models.Model):

    content = models.FileField(verbose_name="ファイル",upload_to="file/")

excel_django/excel/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    
    class Meta:
        model   = Document
        fields  = [ "content" ]

excel_django/excel/views.py
from django.shortcuts import render,redirect
from django.views import View

from .models import Document
from .forms import DocumentForm


from django.http import FileResponse

from django.conf import settings


import datetime


class IndexView(View):
    def get(self, request, *args, **kwargs):

        context = {}
        context["documents"]    = Document.objects.order_by("-id")

        return render(request,"excel/index.html",context)
    
    def post(self, request, *args, **kwargs):

        form    = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("excel:index")

index   = IndexView.as_view()


#TODO:ここにダウンロード時の処理を書く。

import openpyxl as px

class DownloadView(View):
    def get(self, request, *args, **kwargs):
        pass

    def post(self, request, *args, **kwargs):

        #https://docs.djangoproject.com/en/4.0/ref/request-response/#fileresponse-objects

        pk          = kwargs["pk"]
        document    = Document.objects.filter(id=pk).first()

        print(settings.MEDIA_ROOT)
        print(document.content)

        path        = str(settings.MEDIA_ROOT) + "/" + str(document.content) 
        print(path)


        #ここでエクセル読み込み、編集してバイナリデータでFileResponseの引数に入れる。
        wb  = px.load_workbook(path)
        ws  = wb.worksheets[0]

        rows    = ws.iter_rows()

        for row in rows:
            for cell in row:
                print(cell.value)

                #結合されたセルに対しては書き換えできないため、スルーする。
                if type(cell).__name__ == 'MergedCell':
                    continue

                #TODO:ここでコマンドを検知して実行(例えば、command:date を検知して今日の日付を表示させるなど) 
                cell.value  = "書き換えた"


        #一時的に記憶する専用のストレージパスへファイルを保存。FileResponseにてPATHを指定して読み込ませる。
        file_name           = str(datetime.datetime.now()) + ".xlsx"
        temporarily_path    = str(settings.MEDIA_ROOT) + "/temp/" + file_name

        wb.save(temporarily_path)  

        #HACK:一次記憶用のストレージへファイルを保存し続けると、いずれパンクするので、管理サイトか常駐スクリプトから一定時間後に削除させるべきでは？
        return FileResponse( open( temporarily_path, mode="rb" ))


download    = DownloadView.as_view()

excel_django/templates/excel/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>エクセルファイルダウンローダー</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
	<h1 class="text-white bg-primary text-center">エクセルファイルダウンローダー</h1>
        
    
    <main class="container">

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="content">
            <input type="submit" value="送信">
        </form>

        {% for document in documents %}
        <div>
            <a href="{{ document.content.url }}">{{ document.content }}をDL</a>
            
            <form action="{% url 'excel:download' document.id %}" method="POST" style="display:inline-block;">
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="ダウンロード">
            </form>
        </div>
        {% endfor %}

    
    </main>


</body>
</html>